// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeManager.DataAccess;

namespace OfficeManager.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190513231257_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OfficeManager.DataAccess.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adderss");

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("City");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Firstname");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Lastname");

                    b.Property<string>("MobilePhone");

                    b.Property<string>("Nationality");

                    b.Property<string>("PassportNumber");

                    b.Property<string>("PassportSerialNumber");

                    b.Property<string>("RegistrationCity");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adderss = "Test city,Test street,Test home",
                            Birthdate = new DateTime(2019, 5, 13, 23, 12, 55, 933, DateTimeKind.Utc).AddTicks(4378),
                            City = "Test city",
                            Created = new DateTime(2019, 5, 13, 23, 12, 55, 934, DateTimeKind.Utc).AddTicks(182),
                            Firstname = "Test",
                            IsDeleted = false,
                            Lastname = "Test",
                            MobilePhone = "+375291111111",
                            Nationality = "Belarus",
                            PassportNumber = "112233",
                            PassportSerialNumber = "AB",
                            RegistrationCity = "Test registration city",
                            Updated = new DateTime(2019, 5, 13, 23, 12, 55, 934, DateTimeKind.Utc).AddTicks(1680)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
